version: "3"
services:
  mysql:
    image: mysql:${MYSQL_IMAGE_TAG}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  todo:
    image: todo:${TODO_IMAGE_TAG:-latest}
    depends_on:
      - mysql # will not wait for mysql to be “ready” before starting todo-app , It'll only confirm dependency order &
                 # will automatic create dependencies which include in service defination
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql:3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DATABASE}
      TODO_SECURITY_BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      TODO_SECURITY_BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
