version: "3"
services:
  mysql:
    deploy:
      labels:
        name: mysql
        version: ${MYSQL_IMAGE_TAG:-8.0.22}
        component: database
        env: "local"
      placement: 
        constraints: 
          - "node.role == worker"
  todo:
    image: ${TODO_STACK_IMAGE}
    deploy:
      labels:
        name: todo
        version: ${TODO_IMAGE_TAG:-latest}
        component: web
        env: "local" 
      replicas: ${TODO_REPLICA}
      placement: 
        constraints: 
          - "node.role == worker" 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5