management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      sensitive: 'false'
  health:
    defaults:
      enabled: 'true'
    db:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:27017/todo
springdoc:
  api-docs:
    groups:
      enabled: 'true'
todo:
  security:
    basic:
      auth:
        username: local
        password: local
logging:
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M
      - %msg%n'
server:
  error:
    include-message: always
