server:
  port: 8082
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      sensitive: 'false'
  health:
    defaults:
      enabled: 'true'
    db:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
spring:
  application:
    name: todo
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://oauth2.googleapis.com/tokeninfo

springdoc:
  api-docs:
    groups:
      enabled: 'true'

logging:
  level:
    root: INFO
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M
      - %msg%n'