server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      sensitive: 'false'
  health:
    defaults:
      enabled: 'true'
    db:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

logging:
  level:
    root: ERROR
    io:
      github:
        resilience4j:
          circuitbreaker: DEBUG

spring:
  application:
    name: edge
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: google
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            issuer-uri: https://accounts.google.com

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      #failureRateThreshold: 50 # default value if not set
      slowCallRateThreshold: 50
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      waitDurationInOpenState: 10000
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
  instances:
    todoCircuitBreaker:
      baseConfig: default
      waitDurationInOpenState: 5000
      slowCallDurationThreshold: 500