server:
  port: 8080

spring:
  data:
    mongodb:
      uri: "{cipher}S2Fybjphd3M6a21zOmV1LXdlc3QtMjoxMTExMjIyMjMzMzM6a2V5L2JjNDM2NDg1LTUwOTItNDJiOC05MmEzLTBhYThiOTM1MzZkYwAAAADSqo812gHKm22qVq6YXeX6Higf4nH8qc7bnpR3W+ESnzpP5z4XMpDiLiFsy/R1/O9TW4UBgO8zXZvAffAfB72Fd/nU918="


