spring:
  data:
    mongodb:
      uri: "{cipher}S2Fybjphd3M6a21zOmV1LXdlc3QtMjoxMTExMjIyMjMzMzM6a2V5LzQ5YzU0OTJiLWIxYmMtNDJhOC05YTVjLWIyMDE1ZTgxMGMxYwAAAABAY5tMHsyuBg3utEpv38GpwIYUKiIKJvgEARJZ0wqzkmkt3Teda1M62eTwfyqU8R0tg4DWW5cdOkudoiyOJHNFuxQSHpXDKA=="


