spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://redis:6379"
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: google
            clientId: "ci"
            clientSecret: "ci"