version: "3.9"
services:
  mongodb:
    image: mongo
  todo:
    image: todo:2.0.0
    container_name: todo
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongodb
      TODO_SECURITY_BASIC_AUTH_USERNAME: gitci
      TODO_SECURITY_BASIC_AUTH_PASSWORD: gitci
  edge-service:
    image: edge-service:1.0.0
    container_name: edge
    ports:
      - "8081:8081"
