version: "3.9"
services:
  mongodb:
    image: mongo:4.2.21
    ports:
      - "27017:27017"
  todo:
    image: todo:1.0.0
    container_name: todo
    ports:
      - "8080:8080"
    environment:
      TODO_SECURITY_BASIC_AUTH_USERNAME: gitci
      TODO_SECURITY_BASIC_AUTH_PASSWORD: gitci
