version: "3"
services:
  mongodb:
    image: mongo:4.2.21
    ports:
      - "27017:27017"
  todo:
    image: todo:1.0.0
    container_name: todo
    depends_on:
      - mongodb # will not wait for mysql to be “ready” before starting todo-app , It'll only confirm dependency order &
      # will automatic create dependencies which include in service defination
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql:3306
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DB_NAME: todo
      TODO_SECURITY_BASIC_AUTH_USERNAME: gitci
      TODO_SECURITY_BASIC_AUTH_PASSWORD: gitci
