server:
  port: 8080
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        native:
          searchLocations:
            - classpath:/config
            - classpath:/config/{application}
