name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      app_version: "1.0.0"
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # Step that does that actual cache save and restore
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build with Maven
      run: mvn -B package
    - name: Build local image
      run: |
        docker build --tag todo:${{env.app_version}} .
        docker build --build-arg JAR_FILE=build/libs/\*.jar --tag todo:${{env.app_version}} .
    - name: Build local stack
      run: docker-compose -f ci/docker-compose.yaml up -d
    - name: Test local stack
      run: |
        sleep 120
        docker run --network container:todo appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/actuator/health
    - name: Failure Result
      if: ${{ failure() }}
      run: |
        docker logs mysql
        docker logs todo
    - uses: actions-ecosystem/action-push-tag@v1
      name: Push Tag
      with:
        tag: ${{env.app_version}}
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v1
      if: github.ref == 'refs/heads/master'
      with:
        registry: ghcr.io
        username: ${{ secrets.PACKAGE_USERNAME }}
        password: ${{ secrets.PACKAGE_RWD }}
    - name: Docker image push
      if: github.ref == 'refs/heads/master'
      run: |
        docker tag todo:${{env.app_version}} ghcr.io/raghav2211/spring-web-flux-todo-app/todo:${{env.app_version}}
        docker push ghcr.io/raghav2211/spring-web-flux-todo-app/todo:${{env.app_version}}
