name: Build

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'todo-app/k8s/**'
      - 'todo-app/swarm/**'
      - 'todo-app/aws/**'
      - '**/README.md'
      - '.github/**'
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - 'todo-app/k8s/**'
      - 'todo-app/swarm/**'
      - 'todo-app/aws/**'
      - '**/README.md'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo-app

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # Step that does that actual cache save and restore
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build with Maven
      run: mvn -B package
    - name: Build local image
      run: |
        docker build --tag todo .
        docker build --build-arg JAR_FILE=build/libs/\*.jar --tag todo .
    - name: Build local stack
      run: docker-compose --env-file=env/ci/Docker.env -f docker-compose.yaml -f env/local/docker-compose-override.yml up -d
    - name: Test local stack
      run: |
        sleep 120
        docker run --network container:todo appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/actuator/health
    - name: Failure Result
      if: ${{ failure() }}
      run: |
        docker logs mysql
        docker logs todo

      
