name: Pipeline

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
env:
  app_version: "2.0.0"

jobs:
  build-todo-app-maven:
    name: Build app in maven
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Step that does that actual cache save and restore
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        working-directory: ./todo-app
        run: mvn -B package
      - run: |
          mkdir artifact && cp target/*.jar artifact && cp Dockerfile artifact
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: artifact
  build-todo-app-gradle:
    name: Build App in gradle
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        working-directory: ./todo-app
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: ./todo-app
        run: ./gradlew build
  package-artifact-maven:
    name: Create docker image using maven
    runs-on: ubuntu-latest
    needs: [build-todo-app-maven]
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: Package
          path: artifact
      - name: Build local image
        run: |
          ls
          docker build --build-arg JAR_FILE=artifact/todo-${{env.app_version}}.jar --tag todo:${{env.app_version}} .
  package-artifact-gradle:
    name: Create docker image using gradle
    runs-on: ubuntu-latest
    needs: [build-todo-app-gradle]
    permissions:
      contents: read
    steps:
      - name: Build local image
        working-directory: ./todo-app
        run: |
          ls 
          docker build --build-arg JAR_FILE=build/libs/todo-${{env.app_version}}.jar --tag todo:${{env.app_version}} .

