name: Todo App Gradle Pipeline

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
env:
  app_version: "2.0.0"

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir app && cp -R ci app && cp -R todo-app app && cp -R .git app
      - uses: actions/upload-artifact@v2
        with:
          name: Checkout
          path: app        

  build-todo-app:
    name: Build Todo App 
    runs-on: ubuntu-latest
    needs: [checkout]
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: Checkout
          path: app
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Grant execute permission for gradlew
        working-directory: app/todo-app
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: app/todo-app
        run: ./gradlew build
      - run: |
          mkdir -p artifact/todo/gradle && cp app/todo-app/build/libs/todo-${{env.app_version}}.jar artifact/todo/gradle && cp app/todo-app/Dockerfile artifact/todo
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: artifact

  package-todo-app-docker:
    name: Package todo-app
    runs-on: ubuntu-latest
    needs: [build-todo-app]
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: Package
          path: artifact
      - name: Build local image
        working-directory: artifact/todo
        run: |
          docker build --build-arg JAR_FILE=gradle/todo-${{env.app_version}}.jar --tag todo:${{env.app_version}} .
          mkdir -p docker
          docker save todo:${{env.app_version}} > docker/image.tar
      - uses: actions/upload-artifact@v2
        with:
          name: todo-docker-artifact
          path: artifact/todo/docker
  
  push-docker-image-to-github-registry:
    name: Push to Github package registry
    runs-on: ubuntu-latest
    needs: [ package-todo-app-docker ]       
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') && contains(fromJson('["refs/heads/master", "refs/heads/main"]'), github.ref) }}
    steps:
      - name: Download Todo Docker Image
        uses: actions/download-artifact@v2
        with:
          name: todo-docker-artifact
          path: artifact/todo/docker
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGE_USERNAME }}
          password: ${{ secrets.PACKAGE_RWD }}
      - name: Docker image push
        working-directory: artifact
        run: |
          docker load < todo/docker/image.tar
          
          docker tag todo:${{env.app_version}} ghcr.io/raghav2211/spring-web-flux-todo-app/gradle/todo:${{env.app_version}}
          docker push ghcr.io/raghav2211/spring-web-flux-todo-app/gradle/todo:${{env.app_version}}      